---
dns_intname: "eth1"
dns_nameservers:
  - DNS1=172.16.255.254
dns_search: avalon.lan

#Allow firewall services
rhbase_firewall_allow_services:
  - dhcp
dhcp_global_domain_name_servers:
  - 172.16.255.254
dhcp_global_default_lease_time: 28800 #8u
dhcp_global_max_lease_time: 43200 #12u
dhcp_global_subnet_make: 255.255.0.0
dhcp_global_domain_name: avalon.lan

dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    range_begin: 172.16.128.1
    range_end: 172.16.191.254
    deny: 'members of "vbox'
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    range_begin: 172.16.192.1
    range_end: 172.16.255.253
    allow: 'members of "vbox"'

dhcp_global_routers: 172.16.255.254
dhcp_global_classes:
  - name: vbox
    match: 'match if binary-to-ascii(16,8,":",substring(hardware, 1, 3)) = "8:0:27"'

#ADD MAC ADRESS FROM HOST ADAPTER WORKSTATION
dhcp_hosts:
  - name: workstation
    mac: '08:00:27:82:6E:0B'
    ip: 172.16.128.10
