version: '3'

services:

  Drupal:
    image: drupal
    container_name: "Drupal"
    environment: #SETTING DRUPAL
      DRUPAL_PROFILE: standard
      DRUPAL_SITE_NAME: DRUPAL
      DRUPAL_USER: admin
      DRUPAL_PASS: admin
    ports:
      - "8000:80"
    links:
      - database:database
    restart: always

  database:
    image: mariadb
    container_name: "Mariadb"
    environment: #SETTING MARIADB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: drupaldb
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    restart: always

  cadvisor:
    image: google/cadvisor:latest
    container_name: "cAdvisor"
    ports:
      - "8080:8080"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

#Initial setup with portainer
  portainer:
    image: portainer/portainer
    restart: always
    container_name: "Portainer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
    ports:
      - "9000:9000"
